const API_BASE_URL_DEVELOPMENT = 'https://localhost:7128/api'
const API_BASE_URL_PRODUCTION = 'https://aspnetcorewithreact.azurewebsites.net'

const ENDPOINTS = {
    GET_TRENDING : "Movie/GetTrendingMovies",
    GET_CATEGORİES : "Category",      
    GET_MOVIES : "Movie/GetAllMovies?page=",
    GET_MOVIE_BY_ID : "Movie/GetMovieById?movieId=",
    GET_MOVIE_BY_GENRE : "Movie/GetMoviesByCategory?categoryName=",
    GET_STARS_BY_MOVIE_ID : "Star/GetStarsByMovieId?movieId=",
    GET_MOVIE_BY_NAME : "Movie/GetMoviesByName?name=",
};

const development = {
    API_URL_GET_TRENDING : `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_TRENDING}` ,
    API_URL_GET_CATEGORİES : `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_CATEGORİES}` ,
    API_URL_GET_MOVIES : `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_MOVIES}` ,
    API_URL_GET_MOVIE_BY_ID : `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_MOVIE_BY_ID}` ,
    API_URL_GET_MOVIE_BY_GENRE : `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_MOVIE_BY_GENRE}` ,
    API_URL_GET_STARS_BY_MOVIE_ID : `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_STARS_BY_MOVIE_ID}` ,
    API_URL_GET_MOVIE_BY_NAME : `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_MOVIE_BY_NAME}` 
}

const production = {
    API_URL_GET_TRENDING : `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_TRENDING}` ,
    API_URL_GET_CATEGORİES : `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_CATEGORİES}` ,
    API_URL_GET_MOVİES : `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_MOVİES}` ,
    API_URL_GET_MOVİE_BY_ID : `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_MOVİE_BY_ID}` ,
    API_URL_GET_MOVİE_BY_GENRE : `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_MOVİE_BY_GENRE}` ,
    API_URL_GET_STARS_BY_MOVİE_ID : `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_STARS_BY_MOVİE_ID}` ,
    API_URL_GET_MOVİE_BY_NAME : `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_MOVİE_BY_NAME}`,
}

const Constants = process.env.NODE_ENV === 'development' ? development : production ;

export default Constants;